version: '3'
services:
  tower:
    # docker image rm tower ; docker-compose build tower ; docker-compose up -d tower
    # docker exec -ti tower1 ansible --version
    container_name: tower1
    domainname: mystacklab.dev
    hostname: tower1
    image: tower
    volumes:
    - "./tower/ansible:/etc/ansible2"
    build:
      context: tower
    networks:
      - tools_net

  jenkins:
    container_name: jenkins1
    domainname: mystacklab.dev
    hostname: jenkins1
    image: jenkins
    build:
      context: jenkins
    ports:
    - "8081:8080"
    networks:
      - tools_net

  git:
    container_name: git1
    domainname: mystacklab.dev
    hostname: git1
    image: git
    build:
      context: git
    networks:
      - tools_net

  # artifactory:
  #   container_name: artifactory1
  #    domainname: mystacklab.dev
  #    hostname: artifactory1
  #   image: artifactory
  #   build:
  #     context: artifactory
  #   ports:
  #     - "80:80"
  #   networks:
  #     - tools_net
networks:
  tools_net:
